services:
  backend:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: backend
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - gunicorn_socket:/gunicorn/
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./app/movies_database.sql:/docker-entrypoint-initdb.d/movies_database.sql
    env_file:
      - ./app/.env

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:/home/app/web/staticfiles
      - gunicorn_socket:/gunicorn/
    depends_on:
      - backend
    ports:
      - '80:80'

volumes:
  postgres_data:
  static_volume:
  gunicorn_socket:
