version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: backend
    command: sh -c '
      ./entrypoint.sh &&
      ./create_superuser.sh &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    expose:
      - '8000'
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./app/movies_database.sql:/docker-entrypoint-initdb.d/movies_database.sql
    ports:
      - '5435:5432'
    expose:
      - '5435'
    env_file:
      - ./app/.env

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - backend
    ports:
      - '80:80'

volumes:
  postgres_data:
  static_volume:
