version: '3'

services:
  backend:
    build:
      context: ./docker/web
    container_name: backend
#    command: bash -c 'python manage.py migrate
#                      && source create_superuser.sh
#                      && python manage.py runserver 0.0.0.0:8000'
#    command: python manage.py runserver 0.0.0.0:8000
    command: sh -c 'pwd && ls -la'
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - '8000:8000'
    expose:
      - '8000'
    env_file:
      - ./docker/web/.env
    depends_on:
      - db

  db:
    build: ./docker/db
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/db/movies_database.sql:/docker-entrypoint-initdb.d/movies_database.sql
    ports:
      - '5432:5432'
    env_file:
      - ./docker/db/.env
    environment:
      - POSTGRES_DB=$${DB_NAME}
      - POSTGRES_USER=$${DB_USER}
      - POSTGRES_PASSWORD=$${DB_PASSWORD}

# nginx:
#    image: nginx:1.19.2
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
#    depends_on:
#      - backend
#    ports:
#      - '80:80'

volumes:
  postgres_data:
